export type Suit = 'major' | 'cups' | 'wands' | 'swords' | 'pentacles';

export interface TarotCardData {
  name: string;
  suit: Suit;
  numeral?: string;
  number: number;
  keywords: string[];
  upright: string;
  reversed: string;
  symbolism: string;
}

export const SUIT_LABELS: Record<Suit, string> = {
  major: 'Major Arcana',
  cups: 'Cups',
  wands: 'Wands',
  swords: 'Swords',
  pentacles: 'Pentacles',
};

export const SUIT_DESCRIPTIONS: Record<Suit, string> = {
  major: 'The soul\'s journey through archetypal forces',
  cups: 'Emotions, relationships, intuition, and the heart',
  wands: 'Passion, creativity, ambition, and willpower',
  swords: 'Intellect, conflict, truth, and mental clarity',
  pentacles: 'Material world, abundance, craft, and body',
};

const MAJOR_ARCANA: TarotCardData[] = [
  { name: 'The Fool', suit: 'major', numeral: '0', number: 0, keywords: ['beginnings', 'innocence', 'spontaneity', 'free spirit'], upright: 'A leap into the unknown with open-hearted trust. New beginnings call — the universe rewards those who step forward without a map.', reversed: 'Recklessness, naivety, or fear of taking the first step. Something holds you at the edge.', symbolism: 'The cliff edge represents the threshold between the known and unknown. The white rose symbolizes purity of intent. The small dog at the Fool\'s heels is instinct — loyal, alert, urging forward.' },
  { name: 'The Magician', suit: 'major', numeral: 'I', number: 1, keywords: ['manifestation', 'willpower', 'resourcefulness', 'skill'], upright: 'You have everything you need. Channel your focus and the elements align. This is the card of conscious creation.', reversed: 'Manipulation, untapped potential, or scattered energy. The tools are present but unused.', symbolism: 'The infinity symbol above the head represents limitless potential. The four suit symbols on the table — cup, wand, sword, pentacle — show mastery over all elements. One hand points to heaven, the other to earth: "As above, so below."' },
  { name: 'The High Priestess', suit: 'major', numeral: 'II', number: 2, keywords: ['intuition', 'mystery', 'subconscious', 'inner voice'], upright: 'Trust the whisper beneath the noise. Deep knowing lives in the silence between thoughts. The answer is already within you.', reversed: 'Ignoring intuition, secrets, or disconnection from inner wisdom. The veil has thickened.', symbolism: 'She sits between two pillars — B (Boaz, darkness) and J (Jachin, light) — guarding the threshold of the unconscious. The crescent moon at her feet connects her to cycles and tides of emotion. The scroll of Torah represents hidden knowledge.' },
  { name: 'The Empress', suit: 'major', numeral: 'III', number: 3, keywords: ['abundance', 'nurturing', 'fertility', 'nature'], upright: 'Creation flows through you. Abundance is not something to chase — it\'s something to allow. Nurture what matters.', reversed: 'Creative block, dependence, or neglecting self-care. The garden needs tending.', symbolism: 'The lush garden represents fertile ground for growth. The Venus symbol on her shield connects her to love and beauty. The flowing water is emotion in motion — creativity that cannot be contained, only directed.' },
  { name: 'The Emperor', suit: 'major', numeral: 'IV', number: 4, keywords: ['authority', 'structure', 'stability', 'leadership'], upright: 'Build the framework. Authority earned through discipline creates lasting order. Lead with clarity, not force.', reversed: 'Rigidity, domination, or lack of discipline. The throne feels cold without wisdom.', symbolism: 'The stone throne represents permanence and structure. Ram heads symbolize Aries — initiative and authority. The orb and scepter are sovereignty over the material world. Mountains behind him show the immovable foundation of his rule.' },
  { name: 'The Hierophant', suit: 'major', numeral: 'V', number: 5, keywords: ['tradition', 'wisdom', 'spiritual guidance', 'conformity'], upright: 'Seek the teacher within the tradition. There is wisdom in the structures that have endured. Learn before you rebel.', reversed: 'Challenging convention, personal beliefs over dogma, or spiritual stagnation.', symbolism: 'The two pillars echo the High Priestess but in the material temple. The crossed keys at his feet unlock spiritual and earthly knowledge. Two acolytes kneel — representing the transmission of sacred wisdom through lineage.' },
  { name: 'The Lovers', suit: 'major', numeral: 'VI', number: 6, keywords: ['love', 'harmony', 'choices', 'alignment'], upright: 'A choice that aligns head and heart. True union — with another or within yourself. This is the card of sacred alignment.', reversed: 'Disharmony, imbalance, or avoidance of a crucial choice. The heart and mind pull in different directions.', symbolism: 'The angel Raphael blesses the union from above — divine guidance over matters of the heart. The tree of knowledge (with the serpent) and the tree of life represent the eternal dance between desire and wisdom.' },
  { name: 'The Chariot', suit: 'major', numeral: 'VII', number: 7, keywords: ['determination', 'willpower', 'triumph', 'control'], upright: 'Victory through focused will. Opposing forces are harnessed, not eliminated. Move forward with disciplined intensity.', reversed: 'Lack of direction, aggression, or losing control. The horses pull in different directions.', symbolism: 'Two sphinxes — one black, one white — represent opposing forces that must be directed by will alone. The starry canopy connects earthly ambition to celestial purpose. The charioteer wears armor but carries no reins: control comes from within.' },
  { name: 'Strength', suit: 'major', numeral: 'VIII', number: 8, keywords: ['courage', 'patience', 'compassion', 'inner strength'], upright: 'True power is gentle. The lion is not conquered — it is befriended. Courage lives in softness, not force.', reversed: 'Self-doubt, weakness, or raw emotion overwhelming reason. The lion stirs.', symbolism: 'The woman gently closes the lion\'s mouth — not through force but through infinite patience and love. The infinity symbol above her head (like the Magician) shows mastery, but here it is mastery over the self. The white robe is purity of spirit.' },
  { name: 'The Hermit', suit: 'major', numeral: 'IX', number: 9, keywords: ['solitude', 'introspection', 'inner guidance', 'wisdom'], upright: 'Withdraw to find the light within. Solitude is not loneliness — it is the space where truth speaks clearly.', reversed: 'Isolation, withdrawal, or refusing the inner journey. The lantern dims when you avoid looking.', symbolism: 'The lantern holds a six-pointed star — the Seal of Solomon — representing divine wisdom. The mountain peak is spiritual attainment through solitary effort. His grey cloak is invisibility to the outer world while the inner world blazes.' },
  { name: 'Wheel of Fortune', suit: 'major', numeral: 'X', number: 10, keywords: ['cycles', 'destiny', 'turning point', 'luck'], upright: 'The wheel turns. What was down rises; what was up descends. Embrace the cycle — this is a pivotal moment.', reversed: 'Resistance to change, bad luck, or clinging to a passing phase. The wheel turns whether you hold on or not.', symbolism: 'The wheel bears Hebrew letters YHVH (God\'s name) and TARO/ROTA. Four fixed signs of the zodiac sit at the corners — Aquarius, Scorpio, Leo, Taurus — representing stability within change. The sphinx atop holds the sword of discernment.' },
  { name: 'Justice', suit: 'major', numeral: 'XI', number: 11, keywords: ['fairness', 'truth', 'cause and effect', 'law'], upright: 'Truth cuts clean. Every action has its consequence. Seek fairness — in the world and within yourself.', reversed: 'Dishonesty, unfairness, or avoiding accountability. The scales are tipped.', symbolism: 'The sword of truth is double-edged — it cuts both ways. The scales weigh not just actions but intentions. The purple veil behind her hides the mysteries of karmic law. Her crown holds a square — symbol of ordered thought.' },
  { name: 'The Hanged Man', suit: 'major', numeral: 'XII', number: 12, keywords: ['surrender', 'new perspective', 'pause', 'sacrifice'], upright: 'Suspend action to gain vision. What looks like stagnation is actually profound reorientation. Let go to see clearly.', reversed: 'Stalling, martyrdom, or resistance to necessary sacrifice. The pause has become paralysis.', symbolism: 'Hung by one foot from the World Tree, the figure is not in pain but in contemplation. The halo around his head shows enlightenment through surrender. His crossed leg forms a "4" — the number of structure, now inverted.' },
  { name: 'Death', suit: 'major', numeral: 'XIII', number: 13, keywords: ['transformation', 'endings', 'transition', 'release'], upright: 'Something must end for something new to begin. This is not destruction — it is metamorphosis. Release what no longer serves.', reversed: 'Resistance to change, stagnation, or fear of the inevitable. The old skin clings.', symbolism: 'The skeleton knight rides a white horse — purity of the inevitable. The fallen king shows that no earthly power escapes transformation. The rising sun between two towers promises dawn after the darkest passage. The black flag bears a white rose: beauty in endings.' },
  { name: 'Temperance', suit: 'major', numeral: 'XIV', number: 14, keywords: ['balance', 'patience', 'moderation', 'purpose'], upright: 'The middle path holds the deepest magic. Blend opposing forces with patience. Harmony is an active practice, not a passive state.', reversed: 'Imbalance, excess, or lack of long-term vision. The waters spill.', symbolism: 'The angel pours water between two cups — the flow between conscious and unconscious, material and spiritual. One foot on land, one in water: balance between worlds. The path to the distant mountains shows the long road of spiritual alchemy.' },
  { name: 'The Devil', suit: 'major', numeral: 'XV', number: 15, keywords: ['shadow', 'attachment', 'bondage', 'materialism'], upright: 'Face what binds you. The chains are loose — you can remove them. Shadow work begins with honest seeing.', reversed: 'Breaking free, releasing attachments, or confronting addiction. The chains fall.', symbolism: 'The chains around the figures\' necks are loose — they could leave at any time. Baphomet represents the shadow self, not evil but the unconscious forces that control when unacknowledged. The inverted pentagram shows spirit subordinated to matter.' },
  { name: 'The Tower', suit: 'major', numeral: 'XVI', number: 16, keywords: ['upheaval', 'revelation', 'sudden change', 'awakening'], upright: 'What was built on false foundations must fall. The lightning strike is painful but liberating. Truth demolishes illusion.', reversed: 'Fear of change, averting disaster, or prolonging an inevitable collapse.', symbolism: 'Lightning strikes the crown — divine intervention shattering ego structures. The falling figures represent the release of old identities. The tower itself is human ambition built without spiritual foundation. Twenty-two flames fall like the Hebrew letters — the alphabet of creation, rearranging.' },
  { name: 'The Star', suit: 'major', numeral: 'XVII', number: 17, keywords: ['hope', 'inspiration', 'renewal', 'serenity'], upright: 'After the storm, the stars return. Hope is not naive — it is the soul\'s natural state when illusion falls away. You are being renewed.', reversed: 'Despair, disconnection, or loss of faith. The stars are hidden, not gone.', symbolism: 'The naked figure pours water onto land and into the pool — nourishing both the conscious and unconscious. The great star has eight points — regeneration. Seven smaller stars represent the chakras. The ibis in the tree is Thoth — divine wisdom watching over renewal.' },
  { name: 'The Moon', suit: 'major', numeral: 'XVIII', number: 18, keywords: ['illusion', 'fear', 'subconscious', 'intuition'], upright: 'Not everything is as it appears. Navigate by feeling, not sight. The path through uncertainty requires trust in what you cannot yet see.', reversed: 'Clarity emerging, releasing fear, or confronting self-deception. The fog lifts.', symbolism: 'The moon illuminates but also distorts. Two towers mark the gateway to the unknown. The dog and wolf represent the tame and wild aspects of the psyche. The crayfish emerging from the pool is consciousness rising from the deep unconscious.' },
  { name: 'The Sun', suit: 'major', numeral: 'XIX', number: 19, keywords: ['joy', 'success', 'vitality', 'clarity'], upright: 'Radiant clarity. The light reveals everything and there is nothing to fear. Joy, success, and vitality flow naturally now.', reversed: 'Temporary setback, dimmed enthusiasm, or inner child needing attention.', symbolism: 'The child rides freely — innocence restored after the journey through darkness. The sunflowers turn toward the light, representing the soul\'s natural orientation toward truth. The wall represents the boundary between the garden of consciousness and the wild beyond.' },
  { name: 'Judgement', suit: 'major', numeral: 'XX', number: 20, keywords: ['rebirth', 'calling', 'absolution', 'reckoning'], upright: 'The call to rise. Past actions are weighed, and a new chapter begins. Answer the summons of your highest self.', reversed: 'Self-doubt, refusal of the call, or unresolved guilt. The trumpet sounds but you cover your ears.', symbolism: 'The angel Gabriel blows the trumpet of awakening. The dead rise from their coffins — not physical death but the resurrection of the true self from the coffin of conditioning. The flag bears a cross — the intersection of spirit and matter.' },
  { name: 'The World', suit: 'major', numeral: 'XXI', number: 21, keywords: ['completion', 'integration', 'wholeness', 'fulfillment'], upright: 'The cycle is complete. All elements are integrated. You stand at the center of your own universe, whole and fulfilled.', reversed: 'Incompletion, shortcuts, or seeking closure that hasn\'t arrived. The dance isn\'t finished.', symbolism: 'The dancing figure holds two wands — active balance. The laurel wreath is victory and completion. The four creatures at the corners (same as Wheel of Fortune) show that the fixed truths remain, but now you dance within them rather than being turned by them.' },
];

const createMinorCard = (
  suit: Suit,
  number: number,
  name: string,
  keywords: string[],
  upright: string,
  reversed: string,
  symbolism: string
): TarotCardData => ({ name, suit, number, keywords, upright, reversed, symbolism });

const CUPS: TarotCardData[] = [
  createMinorCard('cups', 1, 'Ace of Cups', ['new love', 'compassion', 'emotional awakening', 'creativity'], 'A new emotional beginning overflows. Love, compassion, or creative inspiration pours into your life like water from a divine source.', 'Emotional blockage, emptiness, or repressed feelings. The cup is offered but not received.', 'The hand emerging from the cloud offers the cup of divine love. Five streams overflow — the five senses awakened by spirit. The dove descending with the wafer is the Holy Spirit entering matter through emotion.'),
  createMinorCard('cups', 2, 'Two of Cups', ['partnership', 'unity', 'mutual attraction', 'connection'], 'A sacred bond forms. Two souls meet in mutual recognition and respect. This is the card of true partnership.', 'Imbalance in relationship, broken communication, or separation. The cups no longer mirror each other.', 'Two figures exchange cups — a pledge of emotional reciprocity. The caduceus of Hermes above them represents healing through union. The lion head symbolizes passion tempered by the winged staff of spirit.'),
  createMinorCard('cups', 3, 'Three of Cups', ['celebration', 'friendship', 'community', 'joy'], 'Raise your cup with those who matter. Celebration, sisterhood, and shared joy multiply when given freely.', 'Overindulgence, gossip, or isolation from community. The celebration has lost its meaning.', 'Three figures dance in a circle, cups raised — the trinity of joy in community. Fruits and flowers at their feet represent the harvest of emotional investment in others.'),
  createMinorCard('cups', 4, 'Four of Cups', ['contemplation', 'apathy', 'reevaluation', 'meditation'], 'A pause to reconsider what truly matters. The offered cup may hold exactly what you need — if you look up from your contemplation.', 'Motivation returning, acceptance, or seizing an opportunity previously ignored.', 'The seated figure stares at three cups while a fourth is offered by a divine hand from a cloud. The crossed arms show emotional withdrawal. The tree provides shade — comfort that has become complacency.'),
  createMinorCard('cups', 5, 'Five of Cups', ['grief', 'loss', 'regret', 'disappointment'], 'Grief is real, but not the whole picture. Three cups have spilled, yet two remain standing behind you. Turn around.', 'Acceptance, moving on, or finding meaning in loss. The bridge ahead becomes visible.', 'The cloaked figure mourns three spilled cups but doesn\'t see the two still standing. The bridge in the background leads to safety — the path forward exists but requires turning away from what was lost.'),
  createMinorCard('cups', 6, 'Six of Cups', ['nostalgia', 'innocence', 'childhood', 'reunion'], 'The past returns bearing gifts. Nostalgia, innocence, or a reunion with someone from your history brings unexpected sweetness.', 'Living in the past, unrealistic memories, or inability to move forward. The garden of childhood can become a prison.', 'A child offers a cup filled with flowers to a smaller child — the gift of innocent love. Six cups filled with white flowers represent pure memories. The old house and garden evoke the safety of the past.'),
  createMinorCard('cups', 7, 'Seven of Cups', ['fantasy', 'illusion', 'choices', 'wishful thinking'], 'So many visions, so many possibilities — but which are real? Discernment is needed. Not every glittering cup holds gold.', 'Clarity of purpose, making a choice, or seeing through illusion. The fog of fantasy clears.', 'Seven cups float in clouds, each containing a different vision — wealth, beauty, a castle, a dragon, a wreath, a glowing figure, a serpent. They represent desires, fears, and fantasies that cloud judgment when unexamined.'),
  createMinorCard('cups', 8, 'Eight of Cups', ['departure', 'withdrawal', 'seeking deeper meaning', 'letting go'], 'Walk away from what no longer fills you. The eight cups are neatly stacked but something essential is missing. The mountain calls.', 'Fear of abandonment, clinging, or returning to what was left behind. The journey feels too steep.', 'A figure walks away from eight stacked cups under a waning moon — leaving emotional investments behind in search of deeper meaning. The gap in the cups shows something is missing despite apparent fullness.'),
  createMinorCard('cups', 9, 'Nine of Cups', ['contentment', 'satisfaction', 'wish fulfillment', 'gratitude'], 'The wish card. Emotional satisfaction radiates from within. What you desired has manifested — enjoy it fully and without guilt.', 'Complacency, materialism, or dissatisfaction despite having everything. The smile doesn\'t reach the eyes.', 'The figure sits contentedly before nine cups arranged in an arc — wishes fulfilled, displayed proudly. The crossed arms show self-satisfaction. The blue drape represents emotional depth behind the material display.'),
  createMinorCard('cups', 10, 'Ten of Cups', ['harmony', 'family', 'emotional fulfillment', 'divine love'], 'The rainbow after every storm. Complete emotional fulfillment — family, love, and lasting happiness. The heart\'s deepest wish made real.', 'Broken family, disharmony, or unrealistic expectations of perfection. The rainbow fades.', 'A family celebrates beneath a rainbow of ten cups — the full spectrum of emotional experience integrated into lasting joy. The house and green landscape represent stability and growth. The rainbow is the covenant between human love and divine blessing.'),
  createMinorCard('cups', 11, 'Page of Cups', ['creative opportunity', 'curiosity', 'intuitive message', 'dreamer'], 'A message from the emotional depths arrives unexpectedly. Stay open to creative impulses and intuitive nudges — the fish speaks.', 'Emotional immaturity, creative blocks, or ignoring intuitive messages.', 'The young page looks with surprise at a fish emerging from the cup — the unconscious delivering an unexpected message. The flowing garments and lotus patterns represent emotional sensitivity and creative potential.'),
  createMinorCard('cups', 12, 'Knight of Cups', ['romance', 'charm', 'imagination', 'idealism'], 'The romantic quest. Follow the heart\'s calling with grace and imagination. An offer of love or creative inspiration approaches.', 'Moodiness, unrealistic expectations, or emotional manipulation. The white horse moves but without direction.', 'The knight rides slowly, cup extended like a grail offering. The winged helmet represents imagination in flight. The calm river beneath shows emotions flowing steadily. Unlike other knights, this one moves gently — love cannot be charged at.'),
  createMinorCard('cups', 13, 'Queen of Cups', ['compassion', 'emotional depth', 'intuition', 'nurturing'], 'She sees into the depths of every heart. Compassion without condition, intuition without doubt. Trust your emotional intelligence — it is your greatest gift.', 'Emotional overwhelm, codependency, or martyrdom. The waters rise too high.', 'The queen gazes into an ornate closed cup — she sees what others cannot. Her throne sits at the water\'s edge, where conscious meets unconscious. Cherubs and sea creatures adorn her throne — she rules the emotional realm with gentle authority.'),
  createMinorCard('cups', 14, 'King of Cups', ['emotional balance', 'diplomacy', 'wisdom', 'calm authority'], 'Mastery over the emotional realm. He feels deeply but is not ruled by feeling. Wisdom, diplomacy, and calm authority flow from emotional maturity.', 'Emotional manipulation, volatility, or suppression. The king drowns in his own depths.', 'The king sits on a stone throne amid turbulent seas — unmoved by the chaos around him. He holds a cup in one hand and a scepter in the other: emotional awareness balanced with worldly authority. The fish and ship represent the unconscious and conscious navigating together.'),
];

const WANDS: TarotCardData[] = [
  createMinorCard('wands', 1, 'Ace of Wands', ['inspiration', 'new venture', 'creative spark', 'potential'], 'A bolt of creative fire. New inspiration, a venture, or a passionate beginning ignites. Seize this energy before it passes.', 'Delays, lack of motivation, or creative frustration. The spark struggles to catch.', 'The hand from the cloud grips a living, budding wand — raw creative potential offered by the divine. Leaves fall like sparks. The distant castle represents the achievement possible if this energy is directed.'),
  createMinorCard('wands', 2, 'Two of Wands', ['planning', 'future vision', 'decisions', 'discovery'], 'The world is in your hands. You stand at the threshold of expansion — plan boldly, for the territory ahead is vast.', 'Fear of the unknown, poor planning, or staying in the comfort zone. The globe sits untouched.', 'A figure holds a globe while gazing from a castle battlement — the known world behind, the unknown ahead. Two wands frame the choice: stay safe or venture forth. The red roses and white lilies represent passion and purity of intent.'),
  createMinorCard('wands', 3, 'Three of Wands', ['expansion', 'foresight', 'progress', 'exploration'], 'Your ships are coming in. The seeds you planted are growing beyond your original vision. Expansion is not just possible — it\'s inevitable.', 'Delays in plans, frustration, or lack of foresight. The ships are delayed but not lost.', 'The figure watches ships sail toward distant shores — ventures launched, now in motion. Three wands planted firmly show the foundation of effort. The golden cloak represents success already earned, with more approaching.'),
  createMinorCard('wands', 4, 'Four of Wands', ['celebration', 'homecoming', 'stability', 'harmony'], 'A milestone worth celebrating. The foundation is built, the garland is hung. Welcome home to what you\'ve created.', 'Transition, instability, or feeling unwelcome. The celebration is postponed.', 'Four wands form a canopy draped with garlands and flowers — a threshold of celebration. Figures dance in the background. The castle behind represents the secure foundation that makes joy possible.'),
  createMinorCard('wands', 5, 'Five of Wands', ['conflict', 'competition', 'tension', 'diversity'], 'Creative friction. Five voices, five visions — the clash is not destructive but generative. From this tension, something new emerges.', 'Avoiding conflict, inner turmoil, or resolution of differences. The wands lower.', 'Five figures brandish wands in apparent conflict — but look closer: no one is injured. This is the creative tension of diverse ideas competing for expression. The uneven ground shows unstable but dynamic conditions.'),
  createMinorCard('wands', 6, 'Six of Wands', ['victory', 'recognition', 'triumph', 'confidence'], 'The crowd cheers. Your efforts are recognized and celebrated. Ride this wave of triumph with grace — you\'ve earned it.', 'Ego, fall from grace, or lack of recognition. The laurel slips.', 'A figure rides through a crowd, wand raised with a laurel wreath — public recognition of achievement. The horse represents the drive that carried them to victory. The five followers show that true leadership inspires others.'),
  createMinorCard('wands', 7, 'Seven of Wands', ['perseverance', 'defense', 'standing ground', 'courage'], 'Hold your position. You\'re challenged from below but your higher ground is earned. Defend what matters with fierce conviction.', 'Overwhelm, giving up, or being overrun. The ground beneath feels unstable.', 'A figure stands on a hill, defending against six wands from below — outnumbered but not outmatched. The mismatched shoes show they were caught off guard but rose to the challenge. Higher ground represents moral or strategic advantage.'),
  createMinorCard('wands', 8, 'Eight of Wands', ['swift action', 'momentum', 'rapid progress', 'movement'], 'Everything accelerates. Messages fly, plans materialize, and momentum carries you forward. Don\'t resist the speed — ride it.', 'Delays, frustration, or scattered energy. The wands slow mid-flight.', 'Eight wands fly through clear sky toward the ground — energy in motion, unobstructed. The open landscape below shows no barriers. The river represents the flow of events carrying everything forward with purpose.'),
  createMinorCard('wands', 9, 'Nine of Wands', ['resilience', 'persistence', 'last stand', 'boundaries'], 'You\'ve been through the fire and you\'re still standing. One more challenge remains — draw on your hard-won resilience. The finish line is close.', 'Exhaustion, paranoia, or inability to let guard down. The wounds haven\'t healed.', 'A bandaged figure leans on a wand, eight more behind like a fence — battle-worn but unbroken. The bandage shows past wounds. The defensive posture and watchful eyes show someone who has learned through experience to stay vigilant.'),
  createMinorCard('wands', 10, 'Ten of Wands', ['burden', 'responsibility', 'hard work', 'overwhelm'], 'The weight is real but so is the destination. You carry too much — not because you must, but because you chose to. Set some down.', 'Delegation, release, or burnout. The wands scatter as they fall.', 'A figure carries ten wands toward a distant town — burdened by success, responsibility, or obligation. The bent posture shows the cost of carrying everything alone. The town ahead represents the goal that makes the burden meaningful.'),
  createMinorCard('wands', 11, 'Page of Wands', ['enthusiasm', 'exploration', 'discovery', 'free spirit'], 'A spark of adventure ignites. New ideas, enthusiastic beginnings, and the courage to explore uncharted creative territory.', 'Lack of direction, setbacks, or creative immaturity. The flame flickers.', 'The young page holds a wand and gazes at it with wonder — seeing potential where others see a stick. The desert landscape represents the blank canvas of possibility. Salamanders on the tunic symbolize fire that transforms without being consumed.'),
  createMinorCard('wands', 12, 'Knight of Wands', ['passion', 'adventure', 'impulsiveness', 'energy'], 'Charge forward with passionate intensity. The knight of fire doesn\'t hesitate — action, adventure, and bold moves define this energy.', 'Haste, recklessness, or scattered passion. The horse rears without direction.', 'The knight charges on a rearing horse, wand raised — pure kinetic energy. The desert pyramids in the background represent ancient ambition. Salamanders on the armor (some with tails in mouths) show the cycle of passionate action.'),
  createMinorCard('wands', 13, 'Queen of Wands', ['confidence', 'independence', 'warmth', 'determination'], 'She commands the room without raising her voice. Confident, warm, and fiercely independent — her creative fire inspires everyone around her.', 'Jealousy, selfishness, or demanding nature. The sunflower wilts.', 'The queen sits on a throne adorned with lions and sunflowers — symbols of Leo\'s warmth and courage. The black cat at her feet represents her comfort with shadow and mystery. She holds a sunflower and a wand: beauty and power in equal measure.'),
  createMinorCard('wands', 14, 'King of Wands', ['visionary', 'leadership', 'entrepreneurship', 'honor'], 'The visionary leader. He sees the future and builds toward it with charismatic authority. Bold decisions, entrepreneurial spirit, and natural command.', 'Impulsiveness, tyranny, or unrealistic expectations. The throne burns too hot.', 'The king sits on a throne decorated with lions and salamanders — fire mastered, not extinguished. He holds a living, budding wand — his vision is alive and growing. The salamander at his feet has its tail in its mouth: the eternal cycle of creative destruction and renewal.'),
];

const SWORDS: TarotCardData[] = [
  createMinorCard('swords', 1, 'Ace of Swords', ['clarity', 'breakthrough', 'truth', 'new idea'], 'The sword of truth cuts through confusion. A breakthrough in understanding, a new idea that changes everything. Mental clarity arrives like lightning.', 'Confusion, misinformation, or a truth too painful to face. The sword is dulled.', 'The hand from the cloud grips a sword crowned with a wreath and laurels — victory through truth. The crown represents mental sovereignty. The barren mountains below show that truth exists above the landscape of emotion.'),
  createMinorCard('swords', 2, 'Two of Swords', ['indecision', 'stalemate', 'avoidance', 'difficult choices'], 'The blindfold is self-imposed. You know the truth but refuse to see it. Remove the covering and the choice becomes clear.', 'Information overload, overthinking, or forced decision. The blindfold slips.', 'A blindfolded figure balances two crossed swords — a deliberate refusal to see. The crescent moon behind represents intuition that could guide if allowed. The rocky shore and turbulent water show the emotional cost of indecision.'),
  createMinorCard('swords', 3, 'Three of Swords', ['heartbreak', 'sorrow', 'grief', 'painful truth'], 'The heart pierced by truth. This pain is real and necessary — it clears the way for authentic feeling. Let the rain wash through.', 'Recovery, forgiveness, or releasing old pain. The swords withdraw slowly.', 'Three swords pierce a red heart against grey rain clouds — the most visceral image in the deck. The rain represents tears and emotional release. The heart is not destroyed but pierced: it still beats, transformed by the experience of truth.'),
  createMinorCard('swords', 4, 'Four of Swords', ['rest', 'recovery', 'contemplation', 'solitude'], 'The warrior rests. Not defeat but strategic withdrawal — the mind needs silence to heal. Meditation, recovery, and sacred pause.', 'Restlessness, burnout, or premature return to action. The tomb feels confining.', 'A knight lies in repose on a tomb, hands in prayer — not dead but in deep meditation. Three swords hang above while one lies beneath, showing that one truth has been integrated. The stained glass window depicts a scene of compassion.'),
  createMinorCard('swords', 5, 'Five of Swords', ['defeat', 'conflict', 'betrayal', 'hollow victory'], 'Someone wins, but at what cost? The battle is over and the spoils feel empty. Examine whether the victory was worth the loss.', 'Reconciliation, moving past conflict, or accepting defeat gracefully. The swords are returned.', 'A smirking figure holds three swords while two defeated figures walk away — a hollow victory. The turbulent sky reflects the emotional aftermath. The scattered swords on the ground show that in this conflict, everyone lost something.'),
  createMinorCard('swords', 6, 'Six of Swords', ['transition', 'moving on', 'mental shift', 'healing journey'], 'The boat carries you to calmer waters. Leave the turbulence behind — the journey forward is quiet but necessary. Healing is in motion.', 'Resistance to change, unresolved baggage, or inability to move on. The boat takes on water.', 'A ferryman guides a cloaked figure and child across water — from rough to calm. Six swords stand in the bow like a fence of past pain carried forward. The calm water ahead represents the peace that comes from choosing to move on.'),
  createMinorCard('swords', 7, 'Seven of Swords', ['deception', 'strategy', 'stealth', 'cunning'], 'Not everything is as it seems. Someone moves in shadow — perhaps you, perhaps another. Strategy and discretion are needed, but examine your motives.', 'Coming clean, conscience, or being caught. The stolen swords are too heavy to carry.', 'A figure sneaks away from a camp carrying five swords, leaving two behind — theft, strategy, or necessary cunning. The tents represent the established order being undermined. The figure looks back with a sly expression: is this wisdom or dishonesty?'),
  createMinorCard('swords', 8, 'Eight of Swords', ['restriction', 'imprisonment', 'helplessness', 'self-limiting beliefs'], 'The bonds are loose and the blindfold is thin. You feel trapped but the prison is largely of your own making. One step forward and the swords part.', 'Freedom, new perspective, or breaking free from mental prison. The blindfold falls.', 'A bound and blindfolded figure stands surrounded by eight swords — but the bindings are loose and there is space between the blades. The water at her feet represents emotions that feel overwhelming. The castle on the distant cliff shows that safety exists beyond the perceived prison.'),
  createMinorCard('swords', 9, 'Nine of Swords', ['anxiety', 'nightmares', 'despair', 'mental anguish'], 'The darkest hour before dawn. The swords on the wall are fears projected large by the mind at 3 AM. The suffering is real, but the threat may not be.', 'Hope, recovery, or reaching out for help. The night ends.', 'A figure sits up in bed, face in hands — the classic image of anxiety and sleepless nights. Nine swords hang on the wall behind like a rack of accumulated worries. The quilt is decorated with roses and astrological symbols: beauty and order exist even in the darkest moments.'),
  createMinorCard('swords', 10, 'Ten of Swords', ['endings', 'rock bottom', 'betrayal', 'inevitable conclusion'], 'The final sword falls. This is the absolute end — dramatic, painful, but complete. From this lowest point, the only direction is up. Look at the horizon.', 'Recovery, regeneration, or lessons learned. The dawn breaks over the body.', 'A figure lies face down with ten swords in their back — the most dramatic ending in the deck. But the golden dawn on the horizon promises renewal. The calm water reflects that beneath the drama, peace is already forming. This is not death but the death of a cycle.'),
  createMinorCard('swords', 11, 'Page of Swords', ['curiosity', 'mental agility', 'new ideas', 'vigilance'], 'A sharp mind awakens. Curiosity, quick thinking, and the courage to speak truth — even when it\'s uncomfortable. Watch, learn, then act.', 'Gossip, hasty words, or all talk and no action. The sword is sharp but undirected.', 'The page holds a sword aloft while standing on uneven ground — mentally ready but physically unstable. The windswept clouds show a mind full of ideas. Birds in the sky represent thoughts in flight. The page looks over their shoulder: vigilance and curiosity combined.'),
  createMinorCard('swords', 12, 'Knight of Swords', ['ambition', 'action', 'drive', 'determination'], 'The charge of pure intellect. Swift, decisive, and unstoppable — this energy cuts through hesitation. Act now, refine later.', 'Recklessness, aggression, or burnout from pushing too hard. The horse stumbles.', 'The knight charges at full speed, sword raised — pure intellectual aggression. The stormy sky and windswept trees show the force of this energy. Unlike the Knight of Cups\' gentle approach, this knight believes speed and decisiveness conquer all.'),
  createMinorCard('swords', 13, 'Queen of Swords', ['perception', 'clear boundaries', 'independence', 'direct communication'], 'She sees through every veil. Clear-minded, independent, and unafraid of the truth — her boundaries are her strength. Speak plainly; she\'ll respect you for it.', 'Cold-heartedness, bitterness, or overly critical nature. The sword cuts those she loves.', 'The queen sits on a throne above the clouds — her mind operates above emotional turbulence. She holds the sword upright: truth without apology. The butterfly on her crown represents transformation through mental clarity. Her left hand is open, offering understanding to those who approach honestly.'),
  createMinorCard('swords', 14, 'King of Swords', ['intellectual power', 'authority', 'truth', 'ethical leadership'], 'The mind at its most powerful and disciplined. He judges with fairness, speaks with authority, and leads with intellectual integrity. Truth is his only allegiance.', 'Manipulation, cruelty, or abuse of intellectual power. The throne becomes a cage.', 'The king sits on a throne with butterfly and crescent moon motifs — transformation and intuition supporting pure intellect. His sword tilts slightly to the right: justice tempered by mercy. The clear sky behind him shows a mind unclouded by emotion or agenda.'),
];

const PENTACLES: TarotCardData[] = [
  createMinorCard('pentacles', 1, 'Ace of Pentacles', ['opportunity', 'prosperity', 'new venture', 'manifestation'], 'A golden opportunity materializes. Wealth, health, or a new venture takes physical form. The seed of abundance is in your hands — plant it wisely.', 'Missed opportunity, poor planning, or lack of foresight. The coin slips through fingers.', 'The hand from the cloud offers a golden pentacle over a lush garden — material abundance offered by the divine. The garden archway leads to distant mountains: the path from opportunity to achievement. Lilies represent purity of material intent.'),
  createMinorCard('pentacles', 2, 'Two of Pentacles', ['balance', 'adaptability', 'juggling', 'flexibility'], 'The dance of balance. Multiple demands require fluid adaptation — not rigid control. Embrace the rhythm of change and the juggling becomes effortless.', 'Overwhelm, poor time management, or financial instability. The infinity loop breaks.', 'A figure juggles two pentacles connected by an infinity loop — the eternal dance of balance. Ships ride waves in the background: the ups and downs of material fortune. The figure dances rather than struggles: balance is a dynamic art, not a static achievement.'),
  createMinorCard('pentacles', 3, 'Three of Pentacles', ['teamwork', 'craftsmanship', 'collaboration', 'skill'], 'The master builder at work. Skill, collaboration, and attention to craft create something that endures. Your expertise is recognized and needed.', 'Lack of teamwork, mediocrity, or misaligned goals. The blueprint is ignored.', 'A craftsman works on a cathedral while two figures consult plans — the collaboration of vision, skill, and spiritual purpose. The three pentacles in the arch represent the integration of mind, body, and spirit in material creation.'),
  createMinorCard('pentacles', 4, 'Four of Pentacles', ['security', 'control', 'conservation', 'stability'], 'Hold what you\'ve earned — but not too tightly. Security is important, but when the grip becomes a cage, abundance cannot flow.', 'Generosity, releasing control, or financial insecurity. The pentacles loosen.', 'A figure clutches a pentacle to the chest while sitting on two more, one under each foot — total control over material resources. The city behind is distant: isolation is the cost of hoarding. The crown represents the ego\'s need to possess.'),
  createMinorCard('pentacles', 5, 'Five of Pentacles', ['hardship', 'isolation', 'worry', 'financial loss'], 'The cold outside the church. Material or spiritual poverty weighs heavy — but look up. The stained glass window glows. Help exists for those who ask.', 'Recovery, charity, or spiritual renewal after material loss. The door opens.', 'Two figures trudge through snow past a lit church window — suffering in proximity to help they cannot see or accept. The five pentacles in the window form a Tree of Life pattern: spiritual abundance exists even in material poverty.'),
  createMinorCard('pentacles', 6, 'Six of Pentacles', ['generosity', 'charity', 'giving and receiving', 'balance of resources'], 'The scales of generosity. Give where you can, receive where you must. True abundance flows in both directions — the balance of giving and receiving.', 'Debt, strings attached, or inequality. The scales tip unfairly.', 'A wealthy figure holds scales while distributing coins to kneeling figures — the complex dynamics of wealth, power, and generosity. The scales represent fairness, but the power dynamic is visible: who gives and who receives is never simple.'),
  createMinorCard('pentacles', 7, 'Seven of Pentacles', ['patience', 'assessment', 'investment', 'long-term view'], 'The gardener surveys the harvest. Your investment is growing but not yet ripe. Patience and assessment — is this the crop you truly want?', 'Impatience, poor returns, or wasted effort. The garden underperforms.', 'A figure leans on a hoe, contemplating seven pentacles growing on a vine — the pause between planting and harvest. The figure\'s posture is both tired and contemplative: the cost of patience is visible, but so is the growing reward.'),
  createMinorCard('pentacles', 8, 'Eight of Pentacles', ['diligence', 'mastery', 'skill development', 'dedication'], 'The apprentice becomes the master. Repetition, dedication, and love of craft transform effort into excellence. Keep working — mastery is near.', 'Perfectionism, monotony, or lack of ambition. The chisel dulls.', 'A craftsman carefully carves pentacles one by one — six completed, one in progress, one blank. The city in the distance shows he has withdrawn from the world to focus on his craft. Each pentacle is identical: mastery comes through devoted repetition.'),
  createMinorCard('pentacles', 9, 'Nine of Pentacles', ['luxury', 'self-sufficiency', 'abundance', 'refinement'], 'The garden of earned abundance. Self-sufficiency, luxury, and the quiet confidence of someone who built their own paradise. Enjoy what you\'ve cultivated.', 'Over-dependence, superficiality, or loneliness despite wealth. The garden feels empty.', 'An elegant figure stands in a lush vineyard, a falcon on her wrist — wealth earned through personal effort. The falcon represents intellectual mastery tamed and trained. Nine pentacles grow abundantly: the harvest of disciplined self-reliance.'),
  createMinorCard('pentacles', 10, 'Ten of Pentacles', ['legacy', 'inheritance', 'family wealth', 'establishment'], 'The family tree bears golden fruit. Legacy, inheritance, and the wealth that spans generations. What you build now becomes the foundation for those who follow.', 'Financial failure, family disputes, or loss of legacy. The estate crumbles.', 'An elderly figure sits with family and dogs beneath an archway decorated with ten pentacles in the Tree of Life pattern — generational wealth and wisdom. The tapestry robe represents the rich fabric of family history. Dogs symbolize loyalty across generations.'),
  createMinorCard('pentacles', 11, 'Page of Pentacles', ['ambition', 'desire to learn', 'new financial opportunity', 'studiousness'], 'A student of the material world. New skills, financial opportunities, or the beginning of a practical education. Study with dedication — this seed has enormous potential.', 'Lack of progress, procrastination, or unrealistic goals. The pentacle is admired but not planted.', 'The page holds a pentacle aloft, studying it with intense focus — the beginning of material understanding. The lush green field represents fertile ground for growth. Unlike other pages who look outward, this one is absorbed in the object itself: deep study of how the material world works.'),
  createMinorCard('pentacles', 12, 'Knight of Pentacles', ['reliability', 'hard work', 'routine', 'methodical progress'], 'The steady march of progress. Reliable, methodical, and unwavering — this energy builds empires one brick at a time. Trust the process.', 'Stagnation, laziness, or obsession with routine. The horse stops moving.', 'The knight sits on a stationary dark horse, pentacle held carefully — the only knight who isn\'t moving. The plowed field represents methodical preparation. The heavy armor shows thorough protection. This knight conquers through patience and persistence, not speed.'),
  createMinorCard('pentacles', 13, 'Queen of Pentacles', ['nurturing abundance', 'practical wisdom', 'comfort', 'financial security'], 'She turns everything she touches into gold — not through magic but through practical wisdom and nurturing attention. Abundance flows from her care.', 'Work-life imbalance, neglecting self, or financial dependence. The garden overgrows.', 'The queen sits in a lush garden, cradling a pentacle like a child — material abundance nurtured with love. The rabbit at her feet represents fertility and abundance. Her throne is carved with fruit and angels: the marriage of earthly prosperity and spiritual grace.'),
  createMinorCard('pentacles', 14, 'King of Pentacles', ['wealth', 'business acumen', 'security', 'discipline'], 'The master of the material realm. Wealth built through discipline, business acumen, and patient strategy. His throne is the world itself.', 'Greed, materialism, or financial recklessness. The golden throne becomes a prison.', 'The king sits on a throne decorated with bull heads (Taurus), surrounded by grapevines and his castle — the pinnacle of material achievement. His foot rests on a carved ram: ambition subdued by patience. The pentacle rests easily in his lap: wealth so secure it requires no guarding.'),
];

export const ALL_CARDS: TarotCardData[] = [
  ...MAJOR_ARCANA,
  ...CUPS,
  ...WANDS,
  ...SWORDS,
  ...PENTACLES,
];

/** Draw result with reversed status */
export interface DrawnCard {
  card: TarotCardData;
  isReversed: boolean;
}

/** Pick a single random card from the full 78-card deck, with 30% chance of reversed */
export const drawRandomCard = (): DrawnCard => {
  const idx = Math.floor(Math.random() * ALL_CARDS.length);
  return {
    card: ALL_CARDS[idx],
    isReversed: Math.random() < 0.3,
  };
};

/** Get all card names for sending to the edge function */
export const getAllCardNames = (): string[] =>
  ALL_CARDS.map(c => c.name);

/** Find a card by name */
export const findCardByName = (name: string): TarotCardData | undefined =>
  ALL_CARDS.find(c => c.name.toLowerCase() === name.toLowerCase());

export const getCardsBySuit = (suit: Suit): TarotCardData[] =>
  ALL_CARDS.filter(c => c.suit === suit);

export const searchCards = (query: string): TarotCardData[] => {
  const q = query.toLowerCase().trim();
  if (!q) return ALL_CARDS;
  return ALL_CARDS.filter(c =>
    c.name.toLowerCase().includes(q) ||
    c.keywords.some(k => k.toLowerCase().includes(q)) ||
    c.suit.toLowerCase().includes(q)
  );
};
